repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-yaml
  - id: sort-simple-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: "2.1.4"
  hooks:
  # - id: git-check
  # Figure out how to run this in CI build in order to
  # ensure files that should be updated/modify/generated have been committed
  # - id: git-dirty
  - id: shellcheck
- repo: git://github.com/Bahjat/pre-commit-golang
  rev: master
  hooks:
  - id: gofumpt # requires github.com/mvdan/gofumpt
- repo: git://github.com/golangci/golangci-lint
  rev: master
  hooks:
  - id: golangci-lint
