name: tests
on:
  push:
    paths:
    - '**.go'
    - 'go.mod'
    - 'go.sum'
    - '.github/workflows/tests.yml'
    - 'pkg/**'
    - 'cmd/**'
  pull_request: {}
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        make dl
    - name: Run Unit tests
      run: |
        make cover
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
  precommit:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install tools
      run: |
        make tools
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0
